<a href="https://colab.research.google.com/github/HARSHIT097/Learnings/blob/main/Python_library.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#  numpy Array
---- core library for scientific computation
---- provides high performance multidimensional array, object and tools

In [ ]:
# importing the library
import numpy as np

In [ ]:
#creating arrays
a = np.array([1.5,2,3], dtype = float)
a

array([1.5, 2. , 3. ])

In [ ]:
#create  an array of zeroes
arr_zero = np.zeros((3,4))
arr_zero

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
#create an array of one
arr_one = np.ones((2,3,4))
arr_one

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [ ]:
# creating an array of evenly step or space value
arr_sp = np.arange(10,50,3)
arr_sp

array([10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49])

In [ ]:
#creating number of samples start, stop, no. of samples
arr_sp2 = np.linspace(0,5,9)
arr_sp2
#

array([0.   , 0.625, 1.25 , 1.875, 2.5  , 3.125, 3.75 , 4.375, 5.   ])

In [ ]:
#Create a constant array shape, fill_value
arr_const = np.full((3,3),5)
arr_const

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [ ]:
#creating an array of random values
arr_rand = np.random.random((3,4))
arr_rand

array([[0.54337448, 0.0062408 , 0.81248091, 0.84987485],
       [0.94653683, 0.9888117 , 0.96546906, 0.39331791],
       [0.87548201, 0.45105237, 0.54566264, 0.31635557]])

In [ ]:
#creating an identity matrix
arr_identity = np.eye(5)
arr_identity

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
#array shape n dimension
arr_identity.shape

(5, 5)

In [ ]:
#len of array
len(arr_one)

2

In [ ]:
arr_one.ndim

3

# Pandas

In [ ]:
import pandas as pd


In [ ]:
#Data Structure Series and Data Frame

s = pd.Series([3, -5, 7, 4], index=['a', 'b', 'c', 'd'])
data = {'Country': ['Belgium', 'India', 'Brazil'],
 'Capital': ['Brussels', 'New Delhi', 'Brasília'],
 'Population': [11190846, 1303171035, 207847528]}
df = pd.DataFrame(data,
 columns=['Country', 'Capital', 'Population'])

In [ ]:
print(s)
print("---")
print(df)
print("---")
print(data)

a    3
b   -5
c    7
d    4
dtype: int64
---
   Country    Capital  Population
0  Belgium   Brussels    11190846
1    India  New Delhi  1303171035
2   Brazil   Brasília   207847528
---
{'Country': ['Belgium', 'India', 'Brazil'], 'Capital': ['Brussels', 'New Delhi', 'Brasília'], 'Population': [11190846, 1303171035, 207847528]}


In [ ]:
df.to_csv('myDataFrame.csv')

In [ ]:
data2 = pd.read_csv('myDataFrame.csv' , header=0, nrows=3)
data2

Unnamed: 0  Country    Capital  Population
0           0  Belgium   Brussels    11190846
1           1    India  New Delhi  1303171035
2           2   Brazil   Brasília   207847528

In [ ]:
data2[2:]

Unnamed: 0 Country   Capital  Population
2           2  Brazil  Brasília   207847528

In [ ]:
data2[1:2]

Unnamed: 0 Country    Capital  Population
1           1   India  New Delhi  1303171035

In [ ]:
data2.drop(["Unnamed: 0"], axis =1, inplace=True)

In [ ]:
data2

Country    Capital  Population
0  Belgium   Brussels    11190846
1    India  New Delhi  1303171035
2   Brazil   Brasília   207847528

In [ ]:
data2.sort_values(by="Capital")

Country    Capital  Population
2   Brazil   Brasília   207847528
0  Belgium   Brussels    11190846
1    India  New Delhi  1303171035

In [ ]:
data2.sum(numeric_only=True)

Population    1522209409
dtype: int64

In [ ]:
data2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   Country     3 non-null      object
 1   Capital     3 non-null      object
 2   Population  3 non-null      int64 
dtypes: int64(1), object(2)
memory usage: 200.0+ bytes


In [ ]:
data2.describe()

Population
count  3.000000e+00
mean   5.074031e+08
std    6.961346e+08
min    1.119085e+07
25%    1.095192e+08
50%    2.078475e+08
75%    7.555093e+08
max    1.303171e+09